version: '3.8'
services:
  mongo:
    image: mongo:6.0
    container_name: nosql-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend-node:
    build: ./backend-node
    container_name: nosql-node
    env_file:
      - .env
      - backend-node/.env
    depends_on:
      - mongo
    ports:
      - "${PORT_NODE}:${PORT_NODE}"

volumes:
  mongo-data: