# docker-compose.yml
version: '3.8'

services:
  backend:
    env_file:
      - ./frontend/.env
    build:
      context: ./backend-node
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./backend-node:/app
    image: adi59162/k3_sbd_class:backend
    restart: unless-stopped

  frontend:
    env_file:
      - ./frontend/.env
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    image: adi59162/k3_sbd_class:frontend
    depends_on:
      - backend